14615:   packaging: Restructure how announcement is assembled

diff --git a/packaging/release-sign-tarballs b/packaging/release-sign-tarballs
--- a/packaging/release-sign-tarballs
+++ b/packaging/release-sign-tarballs
@@ -148,25 +148,25 @@ sign_or_fail() {
 
 
 sign_packages() {
-    targz="${PKG_NAME}-${VERSION}.tar.gz"
-    tarbz2="${PKG_NAME}-${VERSION}.tar.bz2"
-    tarxz="${PKG_NAME}-${VERSION}.tar.xz"
-    zip="${PKG_NAME}-${VERSION}.zip"
-    signatures=""
+    tar_name="$1"
+    targz="${tar_name}.tar.gz"
+    tarbz2="${tar_name}.tar.bz2"
+    tarxz="${tar_name}.tar.xz"
+    zip="${tar_name}.zip"
 
     for tarball in $targz $tarxz $tarbz2 $zip; do
 	if [ -e "${tarball}" ]; then
 	    sig="$(sign_or_fail ${tarball})"
 	    gpgsignerr=$((${gpgsignerr} + $?))
 	    sig_url="http://inkscape.org/.../$sig"
-	    signatures="$signatures
+	    cat <<EOF
 https://inkscape.org/en/download/source/
 MD5:  `$MD5SUM $tarball`
 SHA1: `$SHA1SUM $tarball`
 SHA256: `$SHA256SUM $tarball`
 $sig_url
 
-"
+EOF
 	fi
     done
 
@@ -183,13 +183,6 @@ $sig_url
 }
 
 generate_announce() {
-    # TODO: Once converted to git, enable display of shortlog
-    #tag_previous=`git describe --abbrev=0 HEAD^ 2>/dev/null`
-    #tag_range="FIXME..FIXME"
-    #`git log --no-merges "$tag_range" | git shortlog`
-
-    tag_name="$tar_name"
-
     cat <<RELEASE
 Subject: [ANNOUNCE] $PKG_NAME $VERSION
 To: $LIST_TO
@@ -215,17 +208,38 @@ release.  For the full scoop, please see our detailed Release Notes:
 
     http://wiki.inkscape.org/wiki/index.php/Release_notes/$VERSION
 
-git tag: $tag_name
-$signatures
 RELEASE
 }
 
 process() {
     top_src=$(pwd)
 
-    make_dist
-    sign_packages
-    generate_announce > "$tar_name.announce"
+    tar_name=$(make_dist)
+    generate_announce > "${tar_name}.announce"
+
+    # TODO: Once converted to git, enable display of shortlog
+    #tag_previous=`git describe --abbrev=0 HEAD^ 2>/dev/null`
+    #tag_range="FIXME..FIXME"
+    #`git log --no-merges "$tag_range" | git shortlog`
+    echo "${VCS_SYSTEM} tag: $tar_name" >> ${tar_name}.announce
+
+    sign_packages ${tar_name} >> "${tar_name}.announce"
+    if [ $? -ne 0 ]; then
+	rm "${tar_name}.announce"
+	echo "Error: Failed signatures"
+	return 1
+    fi
+
+    # TODO: Verify the top commit SHA has a version bump
+    #     local_top_commit_sha=`git  rev-list --max-count=1 HEAD`
+    #     git diff --unified=0 HEAD^ | $GREP -F $pkg_version >/dev/null 2>&1
+    # TODO: Check that the top commit is pushed to remote
+    #     git  rev-list --max-count=1 $remote_name/$remote_branch
+
+    echo "TODO: Tag the top commit as $tar_name"
+    echo "TODO: Upload the tarballs to the remote"
+    echo "TODO: Push all local changes and tags to remote"
+
     echo "Info: [ANNOUNCE] template generated in \"$tar_name.announce\" file."
     echo "      Please pgp sign and send it."
 
